import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <div className="bg-slate-600 flex flex-col md:justify-center md:items-center h-screen p-12">


            {children}
        </div>
        </body>

    </html>
  )
}
